config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :posts
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :post
  has_many :child_contents, class_name: 'Content', foreign_key: 'parent_content_id'
  belongs_to :parent_content, class_name: 'Content', foreign_key: 'parent_content_id'

  def html_str
    html_tag = html_tags
    mark_tag = mark_tags
    html = []
    html << html_tag[:st] + mark_tag[:st]
    
    if value.present?
      html << value
    else
      if child_contents.present?
        content_html = ""
        child_contents.each{|child_content|
          content_html += child_content.html_str
        }
        html << content_html
      end
    end

    html << html_tag[:et] + mark_tag[:et]
    html.join("")
  end

  private
  def html_tags
    case node_type
    when "document"
      {st: "<div>", et: "</div>"}
    when "paragraph"
      {st: "<p>", et: "</p>"}
    when "list-item"
      {st: "<li>", et: "</li>"}
    when "unordered-list"
      {st: "<ul>", et: "</ul>"}
    else
      {st: "", et: ""}
    end
  end

  def mark_tags
    case marks["type"]
    when "bold"
      {st: "<b>", et: "</b>"}
    when "italic"
      {st: "<i>", et: "</i>"}
    else
      {st: "", et: ""}
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
  has_many :post_tags
  has_many :tags, through: :post_tags
  has_one :content

  def content_html
    content.present? ? content.html_str : ""
  end

  def author_name
    author.present? ? author.name : "N/A"
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags
  has_many :posts, through: :post_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:external_id, :author_id, :title, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NayanPosts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container m-auto p-0">
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :external_id %>
    <%= form.text_field :external_id %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.text_field :author_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="row text-center">
  <div class="col-lg-12 mb-3" style="border-bottom: 5px dashed black;">
    <h1>Posts</h1>
  </div>

  <div class="col-lg-12">
    <% @posts.each do |post| %>
      <div class="col-lg-12 pt-3 pb-3" style="border-bottom: 2px solid grey;">
        <div class="col-lg-12 mb-2"><h4><%= post.title %></h4></div>
        <div class="col-lg-12 mb-2"><%= image_tag(post.image_url, style: "height: 200px; width: 200px;")%></div>
        <div class="col-lg-12 mb-2"><%= link_to 'View Post', post %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="row m-3">
  <div class="col-lg-12 mb-3">
    <%= link_to '< Back', posts_path %>
  </div>
  <div class="col-lg-12 mb-2">
    <h4><%= @post.title %></h4>
  </div>
  <div class="col-lg-12 mb-2">
    <%= image_tag(@post.image_url, style: "height: 200px; width: 200px;")%>
  </div>
  <div class="col-lg-12 mb-2">
    <%= @post.content_html.html_safe %>
  </div>
  <div class="col-lg-12 mb-2">
    <strong>Author:</strong>
    <%= @post.author_name %>
  </div>
  <div class="col-lg-12">
    <strong>Tags:</strong>
    <%= @post.tags.pluck(:name).join(", ") %>
  </div>
</div>